# Generated by Django 4.1.4 on 2023-01-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throttle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='throttlemodel',
            options={'ordering': ['-id'], 'permissions': (), 'verbose_name': 'Throttle', 'verbose_name_plural': 'Throttle'},
        ),
        migrations.AddField(
            model_name='throttlemodel',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='Is Delete', verbose_name='Is Delete'),
        ),
        migrations.AddField(
            model_name='throttlemodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='Update Time', null=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='throttlemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Create Time', null=True, verbose_name='Create Time'),
        ),
    ]
